# Generated by Django 2.2.6 on 2019-10-12 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PGname', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2019, 10, 12, 17, 44, 18, 547016, tzinfo=utc))),
                ('purchasing_office', models.CharField(blank=True, max_length=40, null=True)),
                ('purchasing_item', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
