# Generated by Django 2.2.6 on 2019-10-05 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawling',
            old_name='name',
            new_name='PGname',
        ),
        migrations.RemoveField(
            model_name='crawling',
            name='date',
        ),
        migrations.AddField(
            model_name='crawling',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='crawling',
            name='purchasing_item',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='crawling',
            name='purchasing_office',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='crawling',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
